# Generated by Django 4.2.11 on 2024-03-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_item',
            options={'verbose_name_plural': 'list items'},
        ),
    ]
