# Generated by Django 4.2.11 on 2024-03-15 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0003_alter_list_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_item',
            name='actual_source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shop'),
        ),
        migrations.AddField(
            model_name='list_item',
            name='default_source',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='where_to_buy', to='shopping_list.shop'),
        ),
        migrations.AlterField(
            model_name='list_item',
            name='shopper',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_bought_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
