# Generated by Django 4.2.11 on 2024-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_list_item_actual_source_list_item_default_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_item',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list_item',
            name='quantity_bought',
            field=models.IntegerField(default=0),
        ),
    ]
