# Generated by Django 4.2.11 on 2024-05-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0005_list_item_cancelled_alter_list_item_quantity_bought'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_item',
            options={'ordering': ['date_created'], 'verbose_name_plural': 'list items'},
        ),
    ]
