# Generated by Django 4.2.11 on 2024-05-02 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.utilities


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0006_alter_list_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_item',
            options={'ordering': ['date_created'], 'verbose_name': 'list item', 'verbose_name_plural': 'list items'},
        ),
        migrations.AlterField(
            model_name='category',
            name='creator_id',
            field=models.ForeignKey(default=tools.utilities.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_created_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list_item',
            name='creator',
            field=models.ForeignKey(default=tools.utilities.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_put_item_on_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(default=tools.utilities.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_created_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='creator_id',
            field=models.ForeignKey(default=tools.utilities.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_created_shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
