# Generated by Django 4.2.11 on 2024-05-08 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_list', '0007_alter_list_item_options_alter_category_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_item',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_put_item_on_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_unit',
            field=models.CharField(default='package', max_length=30),
        ),
    ]
