# Generated by Django 4.2.11 on 2024-05-23 11:18

from django.db import migrations
from django.utils.text import slugify

def populate_slug(apps, schema_editor):
    Product = apps.get_model('shopping_list', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            product.slug = slugify(product.product_name)
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0009_product_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug),
    ]
